# Generated by Django 4.2.6 on 2023-12-15 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('junction', '0015_remove_child_enrolled_child_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='staff',
        ),
    ]
